apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-cert
  namespace: demo
spec:
  secretName: demo-tls
  issuerRef:
    name: letsencrypt-route53
    kind: ClusterIssuer
  dnsNames:
  - demo.example.com
