apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-route53
spec:
  acme:
    # Replace with your email
    email: you@example.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-route53-account-key
    solvers:
    - dns01:
        route53:
          region: us-east-1
          # If you want to pin a hosted zone, set hostedZoneID below:
          # hostedZoneID: Z1234567890ABCDE
